CREATE DATABASE SINHVIEN
GO
USE SINHVIEN
GO
CREATE TABLE SV(
MSSV CHAR(10)PRIMARY KEY,
TENSV NVARCHAR(50),
GIOITINH NVARCHAR(10),
DTB FLOAT,
IDlOP INT 
)
CREATE TABLE LOP(
IDLOP INT IDENTITY(1,1) PRIMARY KEY ,
TENLOP NVARCHAR(50)
)
ALTER TABLE SV ADD CONSTRAINT MSSV FOREIGN KEY(IDLOP) REFERENCES LOP(IDLOP)
insert into dbo.LOP

