CREATE DATABASE SINHVIENDAIHOC
GO
use SINHVIENDAIHOC
go
CREATE TABLE SV(
MSSV CHAR(10) NOT NULL PRIMARY KEY,
TENLOP nvarchar(10) NOT NULL,
TENSV NVARCHAR(50) NOT NULL,
GIOITINH bit NOT NULL,
DTB FLOAT NOT NULL,
NGAYSINH DATETIME NOT NULL,
ANH BIT NOT NULL,
HOCBA BIT NOT NULL,
CCCD BIT NOT NULL,
IDlOP INT IDENTITY(1,1), 
)
drop table SV