//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SV
    {
        public string MSSV { get; set; }
        public double DTB { get; set; }
        public string TENSV { get; set; }
        public System.DateTime NGAYSINH { get; set; }
        public string TENLOP { get; set; }
        public int ID_LOP { get; set; }
        public bool GENDER { get; set; }
        public bool ANH { get; set; }
        public bool CCCD { get; set; }
        public bool HOSO { get; set; }
    
        public virtual LSH LSH { get; set; }
    }
}
